name: CI

on:
  pull_request:
    # paths:
    #   - testapp/**

jobs:
  helm-template:
    name: Helm Template Output
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Generate Helm Template
        run: |
          helm template -f testapp/values.yaml ./testapp > /tmp/template_output

      - name: Post Template as PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            const output = fs.readFileSync("/tmp/template_output", "utf8");
            
            const commentBody = `### Helm Template Output
            <details><summary>Show Output</summary>

            \`\`\`yaml
            ${output}
            \`\`\`

            </details>`;
            
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
